controller_manager:
  ros__parameters:
    update_rate: 80 #100  # Hz

    manipulator_position_controllers:
      type: joint_trajectory_controller/JointTrajectoryController
      
    # forward_position_controller:
    #   type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # gripper_controller:
    #   type: position_controllers/GripperActionController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      


# forward_position_controller:
#   ros__parameters:
#     joints:
#       - finger1_joint
#       - finger2_joint
#     interface_name: position     


manipulator_position_controllers:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      

gripper_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - finger1_joint
      - finger2_joint


# gripper_controller:
#   ros__parameters:
#     allow_stalling: True
#     joint: finger1_joint
