controller_names:
  - fake_manipulator_controllers

fake_manipulator_controllers:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
initial:
   manipulator: ready
   #pose: init_pose
   #group: manipulator