manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0001 #vi hat haft den før til 0.0001 måske for småt
  kinematics_solver_timeout: 0.5 # skal måske være højre?
  kinematics_solver_attempts: 5
  position_only_ik: True
#gripper:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  kinematics_solver_attempts: 3
#  position_only_ik: True