trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - manipulator_position_controllers


manipulator_position_controllers:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  #- name: joint_state_broadcaster
   # type: joint_state_broadcaster/JointStateBroadcaster